### ISSUE TITLE
Issue 用のフォームをつくる

### ISSUE THREAD

**Issue by pklion** [ePi5131/patch.aul#32]
[このような](https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)感じで、初心者用に
- バグ
- バグの起こる場合
- エラーログ
- 環境
を書かせるテンプレをつくるとよい？

**Comment by ePi5131** [comment]
GitHubって面白いですね そういうテンプレを作る機能があるんだ
こんな感じでどうでしょうね

**Comment by pklion** [comment]
よいと思います。
もし初心者向けに振るなら yaml 形式で書いた方がフォーム形式になるので決まった形式で書かせやすいかもしれないです
(例) https://github.com/files-community/Files/issues/new?assignees=&labels=feature+request&template=feature_request.yml

```yaml
name: 新機能の提案
description: 既存の挙動を変更する/新しい機能の追加
title: "+ <title>"
labels: [enhancement]
body:
- type: textarea
  attributes:
    label: 背景
    description: どのような理由でこの機能を提案するかの説明
  validations:
    required: true
- type: textarea
  attributes:
    label: 概要
    description: 提案する機能はどのようなものなのかの説明 物によっては画像があると分かりやすい
  validations:
    required: true
- type: textarea
  attributes:
    label: 没案
    description: 他に検討した案
  validations:
    required: true
- type: textarea
  attributes:
    label: その他
    description: 他に書きたいことがあれば
  validations:
    required: false
```
不要ならCloseで大丈夫です。
